#!/usr/bin/env sh

greet() {
    __USED_SHELL="unknown"
    if [ -n "${ZSH_NAME}" ]; then __USED_SHELL="zsh"; fi
    if [ -n "${BASH}" ];     then __USED_SHELL="bash"; fi

    echo ""
    echo "Hello ${USER}."
    echo "I'm a ${__USED_SHELL} window at your service."
    echo ""
}

if [ -n "${ZSH_NAME}" ]; then
    greet
fi
