#!/usr/bin/env sh

alert() {
    # Add an "alert" alias for long running commands. Use like so:
    # sleep 10; alert

    if ( is_machine 'macOS' ); then
        # find sounds in
        # ~/Library/Sounds
        # /System/Library/Sounds

        __CMD='display notification "Work finished."'
        __CMD="${__CMD}"' with title "Terminal"'
        __CMD="${__CMD} sound name \"${1:-Glass}\""

        osascript -e "${__CMD}"
    elif ( is_machine 'linux' ); then
        notify-send -u low 'Terminal work finished.'
    fi
}

if [ -n "${ZSH_NAME}" ]; then
    alert "${@}"
fi
