#!/usr/bin/env sh

is_machine() {
    __MACHINE=$(echo "${1}" | tr '[:upper:]' '[:lower:]')

    case "${__MACHINE}" in
    'macos'|'mac')
        uname --kernel-name | \
        grep --quiet --ignore-case --regexp='darwin.*';
        ;;
    'linux')
        uname --kernel-name | \
        grep --quiet --ignore-case --regexp='linux.*';
        ;;
    *)
        echo "unknown machine: ${1}"
        echo "current machine: $(uname --kernel-name)"
        false
        ;;
    esac
}

if [ -n "${ZSH_NAME}" ]; then
    is_machine "${@}"
fi
