name: cx
on:
  push:
    branches:
      - stable
  pull_request:
    branches:
      - stable
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Build ${{ github.sha }}
        uses: docker/build-push-action@v4
        with:
          context: ./src
          tags: dominicparga/devcontainer:${{ github.sha }},dominicparga/devcontainer:latest
          push: true
      - name: Inspect latest
        run: docker image inspect dominicparga/devcontainer:latest
      - name: Image digest
        run: echo ${{ steps.docker_build.outputs.digest }}
