name: Dotty
on:
  push:
  pull_request:
jobs:
  release:
    if: github.ref == 'refs/heads/release'
    runs-on: ubuntu-latest
    steps:
    - name: Checkout
      uses: actions/checkout@v2
    - name: Setup git-user
      env:
        GIT_USER_NAME: 'GitHub Actions'
        GIT_USER_EMAIL: 'actions@users.noreply.github.com'
      run: |
        git config --global user.name "${GIT_USER_NAME}"
        git config --global user.email "${GIT_USER_EMAIL}"
        git fetch --all
    - name: Deploy and tag
      run: |
        git tag --annotate "v$(cat version)" --message='See CHANGELOG.md'
        git push --tags
